GET http://localhost:5000/secure
Authorization: Bearer EAAXZCCjINcIcBALLoQS5g5pqFiSssOqVsGmln6jtSkSmE9GlfALFgec9YvNVOgszAJgMvn1FmKNkIuKrGtakPCVuhAqfbmVynv0L5PT15T2t2LFK76OJmzOxnd3pD2AoPn8tdruTDpriZB1uqIlPXtqZCS611H0iAZBKVSblU2QYkpNvY9oCRV4GMBDaVp0ZD

GET http://localhost:5000/auth/facebook
Authorization: Bearer EAAXZCCjINcIcBALLoQS5g5pqFiSssOqVsGmln6jtSkSmE9GlfALFgec9YvNVOgszAJgMvn1FmKNkIuKrGtakPCVuhAqfbmVynv0L5PT15T2t2LFK76OJmzOxnd3pD2AoPn8tdruTDpriZB1uqIlPXtqZCS611H0iAZBKVSblU2QYkpNvY9oCRV4GMBDaVp0ZD