POST http://localhost:3333/api/upload-cover
Accept: application/json
Content-Type: multipart/form-data; boundary=MyBoundaryy
Authorization: Bearer {{token}}

--MyBoundaryy
Content-Disposition: form-data; name="file"; filename="image1.png"
Content-Type: image/png

< .\image.png
--MyBoundaryy
Content-Disposition: form-data; name="xxx-hello"

1
--MyBoundaryy--
