
GET http://localhost:3333/api

GET http://localhost:3333/api/forgot-password/send-email?email=hiepxanh@gmail.com



POST http://localhost:3333/api/forgot-password/check-token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3Y2MyNDhiYy04ZDNhLTRmMjMtYjhhYi02YWU5M2MzODQ4YjAiLCJpYXQiOjE2MjI2MDI2OTgsImV4cCI6MTYyMjYwMjk5OH0.gFE_1SMSnGW8islTO2XwAZrJqqRUegTmWcjZxhBlpK4",
    "userId": "7cc248bc-8d3a-4f23-b8ab-6ae93c3848b0",
    "password": "1234"
}

POST http://localhost:3333/api/forgot-password/verify-email
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3Y2MyNDhiYy04ZDNhLTRmMjMtYjhhYi02YWU5M2MzODQ4YjAiLCJpYXQiOjE2MjI2MDI2OTgsImV4cCI6MTYyMjYwMjk5OH0.gFE_1SMSnGW8islTO2XwAZrJqqRUegTmWcjZxhBlpK4",
    "userId": "7cc248bc-8d3a-4f23-b8ab-6ae93c3848b0",
    "password": "1234"
}
