name: 'backend-graphql'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy'
        default: 'staging'
        required: true
      name:
        description: 'build or restart or test'
        default: 'build'
        required: true
  push:
    branches:
      - backend-graphql

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.inputs.name =='test'
    steps:
      - run: |
          echo "environment: ${{ github.event.inputs.environment }}"
          echo "Tags: ${{ github.event.inputs.name }}"
          echo "Tags: ${{ github.event.inputs.name == 'restart' }}"
          echo "Tags: ${{ github.event.inputs.name == 'build' }}"
          echo "Tags: ${{ github.event_name }}"
          echo "Tags: ${{ github.event_name == 'workflow_dispatch' }}"
          echo "staging is true ${{ github.event.inputs.name == 'test' && 'staging' || 'production' }}"
          echo "production is true ${{ github.event.inputs.name == 'test' && 'production' || 'staging' }}"

  restart:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event.inputs.name =='restart'
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: awread.vn
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Restarting client web"}' https://hooks.slack.com/services/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
            dokku ps:restart backend-graphql
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Restart completed"}' https://hooks.slack.com/services/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

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: (github.event_name == 'push' || github.event.inputs.name == 'build')
    steps:
      - name: using action checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Set Git config
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "Github Actions"
      # - name: get latest code from develop
      #   run: |
      #     git fetch --unshallow
      #     git pull
      #     git merge --no-ff origin/develop -m "Auto-merge develop to get latest code"
      #     git push
      #     git push origin backend-graphql:develop

      - name: Using dokku
        uses: dokku/github-action@master
        with:
          # specify `--force` as a flag for git pushes
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@awread.vn:22/backend-graphql'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: noti on failure
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CHANNEL_BOTNET  }}
        # if: always()
        if: failure()
        with:
          channel: '#general'
          status: ${{ job.status }}
          failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) build thất bại cho trang https://backend-graphql.awread.vn'

      - name: noti on success
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CHANNEL_BOTNET  }}
        if: success()
        with:
          channel: '#general'
          status: ${{ job.status }}
          success_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER})  https://backend-graphql.awread.vn sẵn sàng'

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: awread.vn
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Restarting client web"}' https://hooks.slack.com/services/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
            dokku ps:restart reader-web
            dokku ps:restart writer-web
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Restart completed"}' https://hooks.slack.com/services/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
