name: 'reader-web'
on:
  push:
    branches:
      - reader-web

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # specify `--force` as a flag for git pushes
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@awread.vn:22/reader-web'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
