name: 'storybook: writer-web'
on:
  push:
    branches:
      - story-writer-web
  pull_request:
    branches:
      - story-writer-web

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # specify `--force` as a flag for git pushes
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@awread.vn:22/story-writer-web'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  review_app:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    # only run when a pull request is opened
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # create a review app
          command: review-apps:create
          git_remote_url: 'ssh://dokku@awread.vn:22/story-writer-web'
          # specify a name for the review app
          git_push_flags: '--force'
          review_app_name: review-story-writer-web-${{ github.event.pull_request.number }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#build-storybook'
        if: always()
  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Destroy the review app
        uses: dokku/github-action@master
        with:
          # destroy a review app
          command: review-apps:destroy
          git_remote_url: 'ssh://dokku@awread.vn:22/story-writer-web'
          # specify a name for the review app
          review_app_name: review-story-writer-web-${{ github.event.pull_request.number }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
  
        - name: merge this branch to develop
          uses: actions/checkout@v2
        - name: Set Git config
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
        - name: checkout develop then merge
          run: |
            git fetch --unshallow
            git checkout develop
            git pull
            git merge --no-ff story-writer-web -m "Auto-merge story-writer-web back to develop"
            git push
