name: 'storybook: writer-web'
on:
  push:
    branches:
      - story-writer-web
  pull_request:
    branches:
      - story-writer-web

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    if: github.event_name == 'push'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # specify `--force` as a flag for git pushes
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@awread.vn:22/story-writer-web'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: noti building
        uses: edge/simple-slack-notify@master
        if: always()
        with:
          channel: '#build-storybook'
          status: ${{ job.status }}
          success_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) Mời cả lớp thưởng thức bạch tuộc chúa thơm ngon tại: http://story-writer-web.awread.vn'
          failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) Téo teo tèo bạch tuộc chúa nướng thành than... :('
          cancelled_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) AAAAAAA đổi ý không nướng bạch tuộc chúa ăn nữa!'
          fields: |
            [{ "title": "chi tiết PR", "value": "${{ github.event.pull_request.html_url }}", "short": true }]

  review_app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    # only run when a pull request is opened
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: noti building
        uses: edge/simple-slack-notify@master
        if: always()
        with:
          username: 'Bạch Tuộc Nướng'
          text: '${{ github.event.pull_request.user.login }} đang nướng bạch con tuộc số: #${{ github.event.pull_request.number }}-${{ github.event.pull_request.title }}'
          channel: '#build-storybook'
          fields: |
            [{ "title": "Từ bếp", "value": "${{ github.event.pull_request.head.ref }}", "short": true },
            { "title": "Đến bếp", "value": "${{ github.event.pull_request.base.ref }}", "short": true }]
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # create a review app
          command: review-apps:create
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@awread.vn:22/story-writer-web'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # specify a name for the review app
          review_app_name: review-story-writer-web-${{ github.event.pull_request.number }}
      - name: Slack Notification
        uses: edge/simple-slack-notify@master
        if: always()
        with:
          channel: '#build-storybook'
          status: ${{ job.status }}
          success_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) bạch tuộc con chín rồi, mau ăn thôi: http://review-story-writer-web-${{ github.event.pull_request.number }}.awread.vn'
          failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) bạch tuộc con nướng thành than... :('
          cancelled_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) đổi ý không nướng bạch con tuộc ăn nữa!'
          fields: |
            [{ "title": "chi tiết PR", "value": "${{ github.event.pull_request.html_url }}", "short": true }]

  destroy_review_app_on_merged:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: noti building
        uses: edge/simple-slack-notify@master
        if: always()
        with:
          username: 'Bạch Tuộc Nướng'
          text: 'Bắt đầu đi dọn dẹp mâm #${{ github.event.pull_request.number }}, không ăn ở đây nữa nha!!! http://review-story-writer-web-${{ github.event.pull_request.number }}.awread.vn'
          channel: '#build-storybook'
      - name: Destroy the review app
        uses: dokku/github-action@master
        with:
          # destroy a review app
          command: review-apps:destroy
          git_remote_url: 'ssh://dokku@awread.vn:22/story-writer-web'
          # specify a name for the review app
          review_app_name: review-story-writer-web-${{ github.event.pull_request.number }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: noti building
        uses: edge/simple-slack-notify@master
        if: always()
        with:
          username: 'Bạch Tuộc Nướng'
          text: 'Dọn đồ thừa vào mâm chính'
          channel: '#build-storybook'
      - name: merge this branch to develop
        uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: checkout develop then merge
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff story-writer-web -m "Auto-merge story-writer-web back to develop"
          git push

  destroy_review_app_on_close:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
    steps:
      - name: noti building
        uses: edge/simple-slack-notify@master
        if: always()
        with:
          username: 'Bạch Tuộc Nướng'
          text: 'Bắt đầu đi dọn dẹp mâm #${{ github.event.pull_request.number }}, không ăn ở đây nữa nha!!! http://review-story-writer-web-${{ github.event.pull_request.number }}.awread.vn'
          channel: '#build-storybook'
      - name: Destroy the review app
        uses: dokku/github-action@master
        with:
          # destroy a review app
          command: review-apps:destroy
          git_remote_url: 'ssh://dokku@awread.vn:22/story-writer-web'
          # specify a name for the review app
          review_app_name: review-story-writer-web-${{ github.event.pull_request.number }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
