name: 'writer-web'
on:
  push:
    branches:
      - writer-web

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@awread.vn:22/writer-web'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
